image:
  file: Dockerfile
ports:
  - port: 3306
    onOpen: ignore
tasks:
  - name: MySQL
    init: mysqld
  - name: Welcome
    command: >
        mysql -e "create database chat_system";
        mysql < src/chat_system.sql;
        python3 welcome.py;
